name: Screener.in Sector Scraper

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * 1'  # Every Monday 2AM IST

env:
  START_INDEX: ${{ github.event.inputs.start_index || 0 }}
  END_INDEX: ${{ github.event.inputs.end_index || 2500 }}
  MAX_WORKERS: 5

jobs:
  scrape-sectors:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
      run: python sector_ai.py
    
    - name: Upload checkpoint (optional)
      uses: actions/upload-artifact@v4
      with:
        name: checkpoint
        path: checkpoint.txt
